// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://asqpibfprrvwehpqstfk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFzcXBpYmZwcnJ2d2VocHFzdGZrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTExNDgyNjksImV4cCI6MjA2NjcyNDI2OX0.1KudyczOoul1GPf-RjeL3hG-8v_f1vxM152j3Rg9AFQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);